# Generated by Django 5.0.1 on 2024-01-16 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passphrase', models.CharField(max_length=64)),
                ('text_message', models.TextField()),
            ],
        ),
    ]
